FROM node:16.17.0-alpine AS prebuilder

WORKDIR /app

RUN set -eux; \
    apk add python3 make build-base krb5-dev git; \
    git clone https://github.com/mongodb-js/kerberos.git; \
    cd kerberos; \
    npm i; \
    npm run prebuild


FROM node:16.17.0-alpine AS node-kerberos

WORKDIR /app

COPY --from=prebuilder /app/kerberos/prebuilds/*.tar.gz /root/.npm/_prebuilds/

#COPY kerberos-v1.1.5-node-v83-linuxmusl-x64.tar.gz /root/.npm/_prebuilds/f76494-kerberos-v1.1.5-node-v83-linuxmusl-x64.tar.gz

RUN set -eux; \
    apk add krb5 krb5-libs vim curl; \
    mkdir -p /root/.npm/_cacache/_prebuilds
    #ln -s /root/.npm/_prebuilds/f76494-kerberos-v1.1.5-node-v83-linuxmusl-x64.tar.gz /root/.npm/_cacache/_prebuilds/f76494-kerberos-v1.1.5-node-v83-linuxmusl-x64.tar.gz

CMD [ "node" ]
